"""Nested opportunity-reserve policy replay from saved leakage-safe predictions."""
from __future__ import annotations

from datetime import datetime, timezone
import json
from pathlib import Path
import traceback

import numpy as np
import pandas as pd

import adaptive_policy_common as adaptive
import opportunity_reserve_policy_common as reserve


HERE = Path(__file__).resolve().parent
MODEL_ROOT = HERE.parent
OUT_ROOT = MODEL_ROOT / "experiments"
NESTED_RUN = (
    OUT_ROOT / "20260903_162347_617042_adaptive_cumulative_policy_full"
)
NESTED_OOF = NESTED_RUN / "nested_inner_oof_predictions.csv"
OUTER_OOF = (
    OUT_ROOT / "20260903_153740_370305_multicheckpoint_models_full"
    / "oof_predictions.csv"
)


def now() -> str:
    return datetime.now(timezone.utc).isoformat()


def write_record(output: Path, record: dict) -> None:
    (output / "run_record.json").write_text(
        json.dumps(record, indent=2, ensure_ascii=False), encoding="utf-8"
    )


def main() -> None:
    output = OUT_ROOT / (
        datetime.now().strftime("%Y%m%d_%H%M%S_%f")
        + "_saved_nested_opportunity_reserve_policy"
    )
    output.mkdir(parents=True, exist_ok=False)
    configs = reserve.candidate_configs()
    record = {
        "status": "running",
        "started_at": now(),
        "mode": "saved split-safe nested predictions; no model fitting",
        "input_nested_oof": str(NESTED_OOF.resolve()),
        "input_outer_oof": str(OUTER_OOF.resolve()),
        "checkpoints_seconds": list(adaptive.CHECKPOINTS),
        "configuration_count": len(configs),
        "max_budgets": list(reserve.MAX_BUDGETS),
        "base_impact_thresholds": list(reserve.BASE_IMPACT_THRESHOLDS),
        "release_profiles": {
            name: list(values) for name, values in reserve.RELEASE_PROFILES.items()
        },
        "early_premium_profiles": {
            name: list(values)
            for name, values in reserve.EARLY_PREMIUM_PROFILES.items()
        },
        "target_reductions": list(adaptive.TARGET_REDUCTIONS),
        "cost_weights": list(adaptive.COST_WEIGHTS),
        "seed": 42,
        "research_safety": (
            "No RF is refit. For each outer event, policy selection reuses only nested "
            "predictions generated by models excluding both that outer event and each inner "
            "event. Outer OOF outcomes are read only after the policy is frozen. This policy "
            "family was designed after inspecting an earlier outer replay and is therefore "
            "exploratory rather than a fresh confirmatory test."
        ),
    }
    write_record(output, record)
    try:
        print("Starting saved nested opportunity-reserve policy replay.", flush=True)
        print(f"Output directory: {output.resolve()}", flush=True)
        print("[1/7] Loading saved nested and outer event-held-out predictions...", flush=True)
        nested = pd.read_csv(
            NESTED_OOF, dtype={"thread_id": str, "event_id": str, "outer_event": str}
        )
        outer = adaptive.load_outer_oof(OUTER_OOF)
        outer_events = sorted(nested.outer_event.unique())
        missing_outer_scores = set(outer_events) - set(outer.event_id.unique())
        if missing_outer_scores:
            raise ValueError(
                f"nested events missing from outer OOF: {sorted(missing_outer_scores)}"
            )

        print("[2/7] Auditing nested outer/inner isolation and checkpoint coverage...", flush=True)
        if (nested.outer_event == nested.event_id).any():
            raise ValueError("outer event appears in nested policy-selection rows")
        inner_counts = nested.groupby("outer_event").event_id.nunique()
        if not inner_counts.eq(8).all():
            raise ValueError(f"unexpected inner-event counts: {inner_counts.to_dict()}")
        for outer_event, group in nested.groupby("outer_event"):
            adaptive.validate_scored_frame(group.drop(columns="outer_event"))

        inner_metric_chunks = []
        inner_grid_chunks = []
        selected_config_chunks = []
        outer_metric_chunks = []
        outer_selected_chunks = []
        baseline_rows = []
        print("[3/7] Selecting reserve policies inside each outer fold...", flush=True)
        for outer_index, outer_event in enumerate(outer_events, 1):
            print(
                f"  outer event {outer_index}/{len(outer_events)}: {outer_event}; "
                f"evaluating {len(configs)} fixed configurations",
                flush=True,
            )
            inner = nested.loc[nested.outer_event.eq(outer_event)].drop(
                columns="outer_event"
            )
            inner_metrics = reserve.evaluate_configs(inner, configs)
            inner_metrics["outer_event"] = outer_event
            inner_metric_chunks.append(inner_metrics)
            grid = reserve.summarize_grid(inner_metrics)
            grid["outer_event"] = outer_event
            inner_grid_chunks.append(grid)
            selected_configs = adaptive.select_policies(grid.drop(columns="outer_event"))
            selected_configs["outer_event"] = outer_event
            selected_config_chunks.append(selected_configs)

            frozen_metrics, frozen_selected = reserve.apply_selected_policies(
                outer_scores=outer,
                selected_configs=selected_configs,
                outer_event=outer_event,
            )
            outer_metric_chunks.append(frozen_metrics)
            if len(frozen_selected):
                outer_selected_chunks.append(frozen_selected)

            event = outer.loc[outer.event_id.eq(outer_event)]
            fixed = adaptive.fixed_balanced_select(event)
            horizon = float(
                event.loc[event.checkpoint_sec.eq(adaptive.CHECKPOINTS[0]), "future_growth"].sum()
            )
            blocked = float(fixed.dynamic_preventable_impact.sum())
            baseline_rows.append({
                "outer_event": outer_event,
                "policy_name": "fixed_balanced_cumulative_50",
                "config_id": "quotas_9_9_8_8_8_8",
                "max_budget": 50,
                "min_predicted_impact": 0.0,
                "release_profile": "fixed_balanced",
                "early_premium_profile": "none",
                "interventions": 50,
                "positive_interventions": int(fixed.dynamic_preventable_impact.gt(0).sum()),
                "blocked_impact": blocked,
                "horizon_future_at_10m": horizon,
                "horizon_reduction": blocked / horizon if horizon else 0.0,
                "mean_action_minute": float(fixed.action_checkpoint_sec.mean() / 60.0),
                "inner_mean_interventions": np.nan,
                "inner_mean_horizon_reduction": np.nan,
                "inner_worst_event_horizon_reduction": np.nan,
                "used_fallback": False,
            })

        print("[4/7] Aggregating outer-event cost and Pareto results...", flush=True)
        inner_metrics = pd.concat(inner_metric_chunks, ignore_index=True)
        inner_grid = pd.concat(inner_grid_chunks, ignore_index=True)
        selected_configs = pd.concat(selected_config_chunks, ignore_index=True)
        outer_metrics = pd.concat(
            outer_metric_chunks + [pd.DataFrame(baseline_rows)], ignore_index=True
        )
        outer_selected = pd.concat(outer_selected_chunks, ignore_index=True)
        macro = outer_metrics.groupby("policy_name", as_index=False).agg(
            outer_events=("outer_event", "nunique"),
            mean_interventions=("interventions", "mean"),
            max_interventions=("interventions", "max"),
            total_interventions=("interventions", "sum"),
            total_positive_interventions=("positive_interventions", "sum"),
            total_blocked_impact=("blocked_impact", "sum"),
            mean_horizon_reduction=("horizon_reduction", "mean"),
            worst_event_horizon_reduction=("horizon_reduction", "min"),
            mean_action_minute=("mean_action_minute", "mean"),
            fallback_outer_folds=("used_fallback", "sum"),
        ).sort_values(
            ["mean_interventions", "mean_horizon_reduction", "policy_name"],
            ascending=[True, False, True], kind="stable",
        )
        pareto = adaptive.pareto_frontier(macro)

        print("[5/7] Checking caps, selection uniqueness, and result finiteness...", flush=True)
        if (outer_metrics.interventions > outer_metrics.max_budget).any():
            raise ValueError("selected policy exceeded its frozen budget cap")
        if outer_selected.duplicated(
            ["outer_event", "policy_name", "thread_id"]
        ).any():
            raise ValueError("thread selected more than once in an outer policy")
        numeric = outer_metrics[[
            "interventions", "blocked_impact", "horizon_reduction"
        ]].to_numpy(dtype=float)
        if not np.isfinite(numeric).all():
            raise ValueError("non-finite outer policy metric")

        print("[6/7] Writing policy grid, frozen selections, and audit trail...", flush=True)
        inner_metrics.to_csv(output / "inner_policy_metrics.csv", index=False)
        inner_grid.to_csv(output / "inner_policy_grid.csv", index=False)
        selected_configs.to_csv(output / "selected_configs.csv", index=False)
        outer_metrics.to_csv(output / "outer_policy_metrics.csv", index=False)
        outer_selected.to_csv(output / "outer_selected_threads.csv", index=False)
        macro.to_csv(output / "opportunity_reserve_macro.csv", index=False)
        pareto.to_csv(output / "opportunity_reserve_pareto.csv", index=False)

        print("[7/7] Completing result and run record...", flush=True)
        result = {
            "outer_events": outer_events,
            "opportunity_reserve_macro": macro.to_dict(orient="records"),
            "opportunity_reserve_pareto": pareto.to_dict(orient="records"),
            "interpretation_boundary": (
                "Exploratory post-result policy family evaluated with nested selection. "
                "It must not be described as an untouched confirmatory test."
            ),
        }
        (output / "result.json").write_text(
            json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        record.update({
            "status": "complete",
            "completed_at": now(),
            "outer_events": outer_events,
            "inner_event_configuration_rows": len(inner_metrics),
            "selected_policy_rows": len(selected_configs),
            "outer_metric_rows": len(outer_metrics),
            "output_files": [
                "inner_policy_metrics.csv", "inner_policy_grid.csv",
                "selected_configs.csv", "outer_policy_metrics.csv",
                "outer_selected_threads.csv", "opportunity_reserve_macro.csv",
                "opportunity_reserve_pareto.csv", "result.json", "run_record.json",
            ],
        })
        write_record(output, record)
        print(
            "SUCCESS: saved nested opportunity-reserve policy saved to: "
            f"{output.resolve()}",
            flush=True,
        )
    except BaseException as error:
        record.update({
            "status": "failed",
            "failed_at": now(),
            "error": f"{type(error).__name__}: {error}",
            "traceback": traceback.format_exc(),
            "output_files": sorted(path.name for path in output.iterdir()),
        })
        write_record(output, record)
        print(
            "FAILURE: saved nested opportunity-reserve policy preserved at: "
            f"{output.resolve()}",
            flush=True,
        )
        raise


if __name__ == "__main__":
    main()
